In [1]:
import os
import time
import datetime
import pandas as pd
import numpy as np
import sys
from realtabformer import REaLTabFormer

In [2]:

real_data = pd.read_csv('simple_tabular_data.csv')
print(real_data)

     Unnamed: 0  age         workclass  fnlwgt     education  education-num  \
0             0   39         State-gov   77516     Bachelors             13
1             1   50  Self-emp-not-inc   83311     Bachelors             13
2             2   38           Private  215646       HS-grad              9
3             3   53           Private  234721          11th              7
4             4   28           Private  338409     Bachelors             13
..          ...  ...               ...     ...           ...            ...
995         995   56           Private  112840       HS-grad              9
996         996   45           Private   89325       Masters             14
997         997   48       Federal-gov   33109     Bachelors             13
998         998   40           Private   82465  Some-college             10
999         999   39      Self-emp-inc  329980     Bachelors             13

         marital-status         occupation   relationship   race     sex  \
0         Never-married       Adm-clerical  Not-in-family  White    Male
1    Married-civ-spouse    Exec-managerial        Husband  White    Male
2              Divorced  Handlers-cleaners  Not-in-family  White    Male
3    Married-civ-spouse  Handlers-cleaners        Husband  Black    Male
4    Married-civ-spouse     Prof-specialty           Wife  Black  Female
..                  ...                ...            ...    ...     ...
995  Married-civ-spouse    Exec-managerial        Husband  White    Male
996            Divorced     Prof-specialty  Not-in-family  White    Male
997            Divorced    Exec-managerial      Unmarried  White    Male
998  Married-civ-spouse  Machine-op-inspct        Husband  White    Male
999  Married-civ-spouse    Exec-managerial        Husband  White    Male

     capital-gain  capital-loss  hours-per-week native-country income
0            2174             0              40  United-States  <=50K
1               0             0              13  United-States  <=50K
2               0             0              40  United-States  <=50K
3               0             0              40  United-States  <=50K
4               0             0              40           Cuba  <=50K
..            ...           ...             ...            ...    ...
995             0             0              55  United-States   >50K
996             0             0              45  United-States  <=50K
997             0             0              58  United-States   >50K
998          2580             0              40  United-States  <=50K
999         15024             0              50  United-States   >50K

[1000 rows x 16 columns]

In [3]:

numepochs=10
batchsize=10

transformer_model = REaLTabFormer(model_type="tabular",epochs=numepochs,batch_size=batchsize)


transformer_model.fit(real_data)

Computing the sensitivity threshold...
Using parallel computation!!!

/Users/vsekar/AINTEC_Tutorial/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:77: UserWarning: The device=cuda is not available, using device=mps instead.
  warnings.warn(
/Users/vsekar/AINTEC_Tutorial/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:593: UserWarning: Duplicate rate (0.0) in the data is zero. The `qt_interval` will be set                     to qt_interval_unique=100.
  warnings.warn(
/Users/vsekar/AINTEC_Tutorial/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:620: UserWarning: qt_interval adjusted from 100 to 8...
  warnings.warn(

Bootstrap round:   0%|          | 0/500 [00:00<?, ?it/s]

Sensitivity threshold summary:
count    500.000000
mean       0.002063
std        0.009990
min       -0.018939
25%       -0.004848
50%        0.001667
75%        0.007765
max        0.045303
dtype: float64
Sensitivity threshold: 0.020166666666666652 qt_max: 0.05

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

  0%|          | 0/495 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 512 samples generated. Sampling efficiency is: 100.0000%
Critic round: 5,                     sensitivity_threshold: 0.020166666666666652,                         val_sensitivity: 0.008444444444444442,                             val_sensitivities: [0.02181818181818182, 0.00924242424242424, 0.012272727272727272, 0.010303030303030303, 0.004848484848484848, 0.015606060606060604, 0.011363636363636362, 0.02227272727272727, 0.001666666666666665, 0.012575757575757577, -0.006666666666666669, 0.018636363636363635, 0.00015151515151515097, -0.005909090909090911, -0.0015151515151515158]

  0%|          | 0/495 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 512 samples generated. Sampling efficiency is: 100.0000%
Critic round: 10,                     sensitivity_threshold: 0.020166666666666652,                         val_sensitivity: 0.016232323232323233,                             val_sensitivities: [0.023939393939393937, 0.018333333333333333, 0.024090909090909086, 0.02196969696969697, 0.014696969696969694, 0.01893939393939394, 0.02045454545454545, 0.024696969696969696, 0.01303030303030303, 0.014545454545454544, 0.0031818181818181806, 0.02318181818181818, 0.008939393939393938, 0.004696969696969696, 0.008787878787878785]

In [5]:
synthetic_data = transformer_model.sample(len(real_data))

/Users/vsekar/AINTEC_Tutorial/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:77: UserWarning: The device=cuda is not available, using device=mps instead.
  warnings.warn(

  0%|          | 0/1000 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 1024 samples generated. Sampling efficiency is: 100.0000%

In [10]:
print(synthetic_data)

     Unnamed: 0  age         workclass  fnlwgt     education  education-num  \
0           342   34       Federal-gov  221392  Some-college             10
1            71   34           Private  205937   Prof-school             15
2           515   59         Local-gov  194593  Some-college             10
3           141   37           Private  188835  Some-college             10
4           148   30           Private  245942       HS-grad              9
..          ...  ...               ...     ...           ...            ...
995         828   62         Local-gov  153325          10th              6
996         131   31  Self-emp-not-inc  194255       HS-grad              9
997         292   28           Private  166328       HS-grad              9
998         668   58           Private  126365  Some-college             10
999          27   23           Private  186431       HS-grad              9

         marital-status         occupation    relationship  \
0             Separated    Exec-managerial  Other-relative
1    Married-civ-spouse                  ?         Husband
2         Never-married                  ?       Own-child
3              Divorced              Sales   Not-in-family
4    Married-civ-spouse   Transport-moving         Husband
..                  ...                ...             ...
995  Married-civ-spouse                  ?         Husband
996           Separated      Other-service       Unmarried
997       Never-married  Handlers-cleaners       Own-child
998  Married-civ-spouse    Exec-managerial         Husband
999       Never-married      Other-service       Own-child

                   race     sex  capital-gain  capital-loss  hours-per-week  \
0                 White    Male             0             0              30
1    Asian-Pac-Islander    Male             0             0              40
2                 White  Female             0             0              38
3                 White    Male             0             0              40
4                 White    Male             0             0              60
..                  ...     ...           ...           ...             ...
995               White    Male             0             0              40
996               White  Female             0             0              40
997               White    Male             0             0              40
998               White    Male          5000             0              60
999               White  Female             0             0              20

    native-country income
0    United-States  <=50K
1           Mexico   >50K
2    United-States  <=50K
3    United-States  <=50K
4    United-States  <=50K
..             ...    ...
995  United-States  <=50K
996  United-States  <=50K
997  United-States  <=50K
998  United-States   >50K
999  United-States  <=50K

[1000 rows x 16 columns]

In [4]:
synthetic_data.to_csv('rtf_generated_simple_tabular_data.csv', index=True)

NameError: name 'synthetic_data' is not defined