In [1]:
import os
import time
import datetime
import pandas as pd
import numpy as np
import sys
from realtabformer import REaLTabFormer

In [2]:
real_data = pd.read_csv('../data/simple_tabular_data.csv')
print(real_data)

     age         workclass  fnlwgt     education  education-num  \
0     39         State-gov   77516     Bachelors             13
1     50  Self-emp-not-inc   83311     Bachelors             13
2     38           Private  215646       HS-grad              9
3     53           Private  234721          11th              7
4     28           Private  338409     Bachelors             13
..   ...               ...     ...           ...            ...
995   56           Private  112840       HS-grad              9
996   45           Private   89325       Masters             14
997   48       Federal-gov   33109     Bachelors             13
998   40           Private   82465  Some-college             10
999   39      Self-emp-inc  329980     Bachelors             13

         marital-status         occupation   relationship   race     sex  \
0         Never-married       Adm-clerical  Not-in-family  White    Male
1    Married-civ-spouse    Exec-managerial        Husband  White    Male
2              Divorced  Handlers-cleaners  Not-in-family  White    Male
3    Married-civ-spouse  Handlers-cleaners        Husband  Black    Male
4    Married-civ-spouse     Prof-specialty           Wife  Black  Female
..                  ...                ...            ...    ...     ...
995  Married-civ-spouse    Exec-managerial        Husband  White    Male
996            Divorced     Prof-specialty  Not-in-family  White    Male
997            Divorced    Exec-managerial      Unmarried  White    Male
998  Married-civ-spouse  Machine-op-inspct        Husband  White    Male
999  Married-civ-spouse    Exec-managerial        Husband  White    Male

     capital-gain  capital-loss  hours-per-week native-country income
0            2174             0              40  United-States  <=50K
1               0             0              13  United-States  <=50K
2               0             0              40  United-States  <=50K
3               0             0              40  United-States  <=50K
4               0             0              40           Cuba  <=50K
..            ...           ...             ...            ...    ...
995             0             0              55  United-States   >50K
996             0             0              45  United-States  <=50K
997             0             0              58  United-States   >50K
998          2580             0              40  United-States  <=50K
999         15024             0              50  United-States   >50K

[1000 rows x 15 columns]

In [3]:

numepochs=10
batchsize=10

transformer_model = REaLTabFormer(model_type="tabular",epochs=numepochs,batch_size=batchsize)


transformer_model.fit(real_data)

Computing the sensitivity threshold...
Using parallel computation!!!

/home/steven/Projects/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:593: UserWarning: Duplicate rate (0.0) in the data is zero. The `qt_interval` will be set                     to qt_interval_unique=100.
  warnings.warn(
/home/steven/Projects/generative-trace-tutorials/src/realtabformer/src/realtabformer/realtabformer.py:620: UserWarning: qt_interval adjusted from 100 to 8...
  warnings.warn(

Bootstrap round:   0%|          | 0/500 [00:00<?, ?it/s]

Sensitivity threshold summary:
count    500.000000
mean       0.001792
std        0.009200
min       -0.019091
25%       -0.005152
50%        0.000909
75%        0.007879
max        0.034242
dtype: float64
Sensitivity threshold: 0.01818181818181818 qt_max: 0.05

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

  0%|          | 0/495 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 512 samples generated. Sampling efficiency is: 100.0000%
Critic round: 5,                     sensitivity_threshold: 0.01818181818181818,                         val_sensitivity: 0.014404040404040402,                             val_sensitivities: [0.008636363636363635, 0.0003030303030303011, -0.0034848484848484856, -0.006363636363636365, 0.006363636363636361, 0.028484848484848484, 0.025454545454545452, 0.02696969696969697, 0.02121212121212121, 0.02712121212121212, 0.0356060606060606, 0.013484848484848481, 0.007272727272727273, 0.010454545454545452, 0.014545454545454544]

  0%|          | 0/495 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 512 samples generated. Sampling efficiency is: 100.0000%
Saving not-best model...
Critic round: 10,                     sensitivity_threshold: 0.01818181818181818,                         val_sensitivity: 0.01977777777777778,                             val_sensitivities: [0.02803030303030303, 0.01590909090909091, 0.006212121212121212, 0.0027272727272727258, 0.030606060606060605, 0.020454545454545454, 0.02015151515151515, 0.01409090909090909, 0.017575757575757578, 0.021060606060606057, 0.048939393939393935, 0.026060606060606062, 0.018636363636363635, 0.01621212121212121, 0.009999999999999998]

In [4]:
synthetic_data = transformer_model.sample(len(real_data))

  0%|          | 0/1000 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 1024 samples generated. Sampling efficiency is: 100.0000%

In [5]:
print(synthetic_data.head())

   age  workclass  fnlwgt education  education-num         marital-status  \
0   23    Private  178192   5th-6th              3          Never-married
1   34  Local-gov  121760   HS-grad              9  Married-spouse-absent
2   27    Private  308735   HS-grad              9          Never-married
3   33    Private  265864   HS-grad              9          Never-married
4   19    Private  153829   HS-grad              9          Never-married

      occupation    relationship   race     sex  capital-gain  capital-loss  \
0  Other-service  Other-relative  White    Male             0             0
1              ?       Unmarried  White  Female             0             0
2   Craft-repair   Not-in-family  White    Male             0             0
3          Sales            Wife  White  Female             0             0
4  Other-service   Not-in-family  White    Male             0             0

   hours-per-week native-country income
0              20         Mexico  <=50K
1              40  United-States  <=50K
2              40  United-States  <=50K
3              40  United-States  <=50K
4              30  United-States  <=50K

In [6]:
synthetic_data.to_csv('../data/generated_rtf_simple_tabular_data.csv', index=False)